import random


def play_match(a, b, ia, ib):
    team1_match_score = -1
    team2_match_score = -1
    first_match = True
    while (team1_match_score == team2_match_score):
        if (not first_match): print('And it is a draw!!\n Match must be replayed')
        print('Now playing ' + a + '  vs  ' + b)
        team1_match_score = random.randrange(0, 10)
        team2_match_score = random.randrange(0, 10)
        print('match results ' + str(team1_match_score) + 'team2_match_score' + str(team2_match_score))
        first_match = False
    if team1_match_score > team2_match_score:
        print('Winner is team ' + a + '\n\n')
        return [ia, (ia, ib, team1_match_score, team2_match_score, ia)]
    else:
        print('Winner is team ' + b)
        return [ib, (ia, ib, team1_match_score, team2_match_score, ib)]


def print_match(match):
    print('\n\nThere was a match')
    print('Between ' + team_mas[match[0]] + ' and ' + team_mas[match[1]])
    print('Score was ' + str(match[2]) + 'x' + str(match[3]))
    print('Winner was ' + team_mas[match[4]])
    return


input_val = -1
while (not (input_val == 0 or input_val == 1)):
    input_val = input('Print 0 to use autogenerated team mas\nPrint 1 to input teammas manualy\n')
    input_val = int(input_val)

colvo_of_teams = 0
if input_val == 0:
    team_mas = ['t0', 't1', 't2', 't3', 't4', 't5', 't6', 't7']
    colvo_of_teams = 8
else:
    team_mas = []
    avalible_numbers = (2, 4, 8, 16, 32)
    colvo_of_teams = 0
    flag = False
    while (not flag):
        colvo_of_teams = input("Input teams number! \n It must be: 2 or 4 or 8 or 16 or 32 \n")
        colvo_of_teams = int(colvo_of_teams)
        if colvo_of_teams in avalible_numbers:
            flag = True
    print(' \n\nNow please enter ' + str(colvo_of_teams) + ' teams\n\n')
    for j in range(0, colvo_of_teams):
        tmp = input('Input team' + str(j) + ' name \n')
        team_mas.append(tmp)
    print('\n\n Finished team inputing\n')

print('\n\n Printing team info\n')

for i in range(0, colvo_of_teams):
    print(str(i) + "-" + team_mas[i] + "\n")

print('\n\n Now making new order')

order_of_teams = []
i = 0
while (i != colvo_of_teams):
    tmp = random.randrange(0, colvo_of_teams)
    if tmp not in order_of_teams:
        order_of_teams.append(tmp)
        print(order_of_teams)
        i += 1

print('\n\n Printing new order')
for i in order_of_teams:
    print(str(i) + ' - ' + team_mas[i])

print('\n\n Now Matching')

matches = []
new_order = []

while (colvo_of_teams != 1):
    print('\n\nNow is 1/' + str(colvo_of_teams) + ' part of final')
    print('\n Mathces that will be played')
    for i in range(0, colvo_of_teams, 2):
        print('\n ' + team_mas[order_of_teams[i]] + '  vs  ' + team_mas[order_of_teams[i + 1]])
    print('\n\n Playing 1/' + str(colvo_of_teams) + ' matches')
    for i in range(0, colvo_of_teams, 2):
        tmp = play_match(team_mas[order_of_teams[i]], team_mas[order_of_teams[i + 1]], order_of_teams[i],
                         order_of_teams[i + 1])
        print('\n')
        new_order.append(tmp[0])
        matches.append(tmp[1])
    order_of_teams = new_order
    new_order = []
    colvo_of_teams = colvo_of_teams // 2

print('\n\nWinner of the championship is ' + team_mas[matches[len(matches) - 1][4]])

input_val = ""
while (input_val != -1):
    input_val = input('\n\ninput index of comand or -1 to exit\n')
    if (input_val == -1):
        break
    x = int(input_val)
    for i in matches:
        if (i[0] == x or i[1] == x):
            print_match(i)
