# На входе есть список команд. Его вы задаете сами любым удобным способом.
# Далее вы случайным образом (модуль random) разбиваете команды по парам и формируете сетку
# плей-офф - думаю все знают, как проводятся такие турниры (1/8-я, 1/4-я, полуфиналы и финал).
# Далее проводите матчи - счет определяется случайным образом. По окончании турнира нужно иметь возможность
# запросить и посмотреть как выступила в турнире та или иная команда - с кем на какой стадии играла, счет матча.
# Если что-то непонятно по условию - спросите и я уточню.
import random


def play_match(a, b, ia, ib):
    z = x = -1
    first = True
    while (z == x):
        if (not first): print('And it is a draw!!\n Match must be replayed')
        print('Now playing ' + a + '  vs  ' + b)
        z = random.randrange(0, 10)
        x = random.randrange(0, 10)
        print('match results ' + str(z) + 'x' + str(x))
        first = False;
    if z > x:
        print('Winner is team ' + a + '\n\n')
        return [ia, (ia, ib, z, x, ia)]
    else:
        print('Winner is team ' + b)
        return [ib, (ia, ib, z, x, ib)]


def print_match(match):
    print('\n\nThere was a match')
    print('Between ' + team_mas[match[0]] + ' and ' + team_mas[match[1]])
    print('Score was ' + str(match[2]) + 'x' + str(match[3]))
    print('Winner was ' + team_mas[match[4]])
    return


inp=-1
while(not (inp=='0' or inp=='1')):
    inp=input('Print 0 to use autogenerated team mas\nPrint 1 to input teammas manualy\n')

col = 0
if inp=='0':
    team_mas = ['t0', 't1', 't2', 't3', 't4', 't5', 't6', 't7']
    col=8
else:
    team_mas =[]
    avalible_numbers = (2, 4, 8, 16, 32)
    col = 0
    flag = False
    while(not flag):
       col=input("Input teams number! \n It must be: 2 or 4 or 8 or 16 or 32 \n")
       col=int(col)
       if col in  avalible_numbers:
           flag=True
    print(' \n\nNow please enter ' + str(col) + ' teams\n\n')
    for j in range(0,col):
       tmp=input('Input team'+str(j)+' name \n')
       team_mas.append(tmp)
    print('\n\n Finished team inputing\n')


print('\n\n Printing team info\n')

for i in range(0, col):
    print(str(i) + "-" + team_mas[i] + "\n")

print('\n\n Now making new order')

order = []
i = 0
while (i != col):
    tmp = random.randrange(0, col)
    if not tmp in order:
        order.append(tmp)
        print(order)
        i += 1

print('\n\n Printing new order')
for i in order:
    print(str(i) + ' - ' + team_mas[i])

print('\n\n Now Matching')

matches = []
new_order = []

while (col != 1):
    print('\n\nNow is 1/' + str(col) + ' part of final')
    print('\n Mathces that will be played')
    for i in range(0, col, 2):
        print('\n ' + team_mas[order[i]] + '  vs  ' + team_mas[order[i + 1]])
    print('\n\n Playing 1/' + str(col) + ' matches')
    for i in range(0, col, 2):
        tmp = play_match(team_mas[order[i]], team_mas[order[i + 1]], order[i], order[i + 1])
        print('\n')
        new_order.append(tmp[0])
        matches.append(tmp[1])
    order = new_order;
    new_order = []
    col = col // 2

print('\n\nWinner of the championship is ' + team_mas[matches[len(matches) - 1][4]])


#print(matches)

inp = ""
while (inp != "out"):
    inp = input('\n\ninput index of comand or "out" to exit\n')
    if (inp == 'out'):
        break
    x = int(inp)
    for i in matches:
        if (i[0] == x or i[1] == x):
            #print('\n\nThere was a match')
            #print('Between ' + team_mas[i(0)] + ' and ' + team_mas[i(1)])
            #print('Score was ' + str(i(2)) + 'x' + str(i(3)))
            #print('Winner was' + team_mas[i(4)])
            print_match(i)
